In [1]:
import numpy as np

In [2]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [5]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [8]:
arr=np.array([1,2,3,4,5,"vanshika"])
print(arr,type(arr),arr.dtype)

['1' '2' '3' '4' '5' 'vanshika'] <class 'numpy.ndarray'> <U21


In [12]:
arr=np.array(([1,2,3],[2,3,4],[5,6,9]))
print(arr,arr.shape,type(arr))

[[1 2 3]
 [2 3 4]
 [5 6 9]] (3, 3) <class 'numpy.ndarray'>


In [40]:
arr=np.zeros((3,3),dtype="int32")
print(arr)
print()
arr1=np.ones((3,3),dtype="int32")
print(arr1)
print()
arr2=np.full((3,3),4,dtype="int32")
print(arr2)
print()
arr3=np.eye((5),dtype="int32")
print(arr3)



[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[4 4 4]
 [4 4 4]
 [4 4 4]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [41]:
arr4=np.ones((3,3),dtype="int32")
print(arr4)
print()
arr5=np.arange(1,13,2)
print(arr5)
print()
arr6=np.linspace(1,100,3)
print(arr6)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[ 1  3  5  7  9 11]

[  1.   50.5 100. ]
